export const TODO_LIST_STATE = 'TODO_LIST_STATE';
export const TODO_LIST_FILTER_STATE = 'TODO_LIST_FILTER_STATE';
export const FILTERED_TODO_LIST_STATE = 'FILTERED_TODO_LIST_STATE';
export const TODO_LIST_STATS_STATE = 'TODO_LIST_STATS_STATE';
export const LOADING_LIST = 'LOADING_LIST';